name: PropertyGuru Engineering
url: https://propertyguru.github.io
description: PropertyGuru's Engineering Blog
author: PropertyGuru
keywords:

permalink: /:year/:month/:day/:title/
paginate: 2
highlighter: rouge

gems:
  - jekyll-sitemap
  - jekyll-paginate

exclude: ['README.md', 'Gemfile.lock', 'Gemfile', 'Rakefile', 'CNAME']